### ISSUE TITLE
Feature Request: ingest "already seen" classification metadata flag

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/eras#78]
Context: a series of individuals with high classification counts was investigated and identified to be unwanted behavior. One  distinguishing feature of the high-rate classification behavior being unwanted: many of the subjects were flagged as "already seen" and fallback subjects were each classified many times.

Feature Request: add ingest of "already seen" metadata as binary flag on classification_events table as way to identify and track possible abusive behavior.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added already_seen boolean field to ClassificationEvent model to track if a subject was already seen by the user. This allows identifying potentially unwanted high-rate classification behavior.

You can review changes in this commit: https://github.com/lattaai13/zooniverse-eras-78/commit/339a6bbc183f6e4db1986db19f7afe7da4a94257.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by yuenmichelle1** [comment]
Closed with #80
